### PR TITLE
Adding Google SSO

### PR DESCRIPTION
**Pull request by anievesj**
[CLI-70](https://linear.app/clique-friends-app/issue/CLI-70/google-sso-authentication)

## Summary
Added Google SSO

## Developer Notes
It works

## Future
N/A

## PR Checklist
N/A

- [x] Correct merge branch
- [x] Code approved

### CODE REVIEW

**Review by apatwary12 — APPROVED** [review]
LGTM c:

**Comment by Howardk97** [comment]
Great job adding the Google SSO! When I tested it on a browser not signed into a google account, it worked beautifully. However, when the browser was signed into a google account, it did not give an option to enter google credentials and the page just automatically created an account with the google credentials on the browser. I attached a screen recording so you can see what I am describing.

https://drive.google.com/file/d/1Olyss8BTvvRSNfDGOlfBddB_YgV4R2oE/view?usp=sharing

This is a bug that should be fixed as we always want the user to choose the google account they are signing up with even if they are already logged into a google account on their browser.

**Comment by Howardk97** [comment]
Issue has been resolved. Great job!

**Review by Howardk97 — COMMENTED** [review]
Great Job!

**Review by Howardk97 — COMMENTED** [review]
Approved!

**Review by Howardk97 — APPROVED** [review]
Approved!

**Pull request merged**
